name: Go

on:
  push:
    branches: 
    - main
    - release/*
    - devs/*
  pull_request:
    branches: 
    - main
    - release/*
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2,14 * * *'
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v .
    - name: Upload Asset (on release)
      # You may pin to the exact commit or the version.
      # uses: PeerXu/upload-asset@ac15234d94a4bfc9b33e1e98573fb470553ed809
      if: ${{ github.event_name == 'release' }}
      uses: PeerXu/upload-asset@v1
      with:
        # which file to upload
        file: trouvetonstaff
        # file suffix
        suffix: ''
        # which operating system platform for file to execute
    #- name: Test
    #  run: go test -v ./...
